In [3]:
x = 1
y = 2
z = x+3

In [4]:
z

4

In [5]:
def add_numbers(x,y):
    z = x + y
    return z

In [6]:
sums = add_numbers(2,3)

In [7]:
sums

5

In [8]:
import csv
%precision 2
import os
print(os.getcwd())
# from datasets import 'mpg.csv'
with open('/home/nitin/work/coursera_python_datascience/resources/course1/week-1/datasets/mpg.csv') as csv_file:
    mpg = list(csv.DictReader(csv_file))
mpg[:3]    

/home/nitin/work/coursera_python_datascience/resources/course1/week-1


[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

In [9]:
len(mpg)


234

In [10]:
mpg[0].keys()

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [11]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [12]:
str = 'ConexusDelivery_HH_YYYYMMDD_XX.csv.gz'
file_name = str.split('.')[0]
file_breakdown = file_name.split('_')
hour = file_breakdown[1]
ymd = file_breakdown[2]
year = ymd[:4]
month = ymd[4:6]
day = ymd[6:8]
print(f'{year} {month} {day} {hour}')

YYYY MM DD HH


In [13]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

In [14]:
cylinders = set( d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [15]:
ctyMlgPerCyl = []
for c in cylinders:
    summpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyltypecount += 1
    ctyMlgPerCyl.append((c, summpg/cyltypecount))
ctyMlgPerCyl.sort(key=lambda x : x[0])
ctyMlgPerCyl
            

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [16]:

classes = set( d['class'] for d in mpg)
classes

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [17]:
ctyMpgPerCls = []
for c in classes:
    summpg = 0
    clsTypeCount = 0
    for d in mpg:
        if d['class'] == c :
            summpg += float(d['cty'])
            clsTypeCount += 1
    ctyMpgPerCls.append((c, summpg/clsTypeCount))
ctyMpgPerCls.sort(key=lambda x : x[0])
ctyMpgPerCls

[('2seater', 15.40),
 ('compact', 20.13),
 ('midsize', 18.76),
 ('minivan', 15.82),
 ('pickup', 13.00),
 ('subcompact', 20.37),
 ('suv', 13.50)]

In [18]:
import numpy as np
import math

In [19]:
b = np.array([1,2,3,4])
b.ndim

1

In [20]:
b

array([1, 2, 3, 4])

In [21]:
b.shape


(4,)

In [22]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c.shape

(3, 3)

In [23]:
c.ndim



2

In [24]:
d = np.array([[[1,2,3.4],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
d.shape

(2, 3, 3)

In [25]:
d.ndim

3

In [26]:
d.dtype

dtype('float64')

In [27]:
d

array([[[1. , 2. , 3.4],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [7. , 8. , 9. ]]])

In [28]:
f = np.arange(10, 50, 2)
print(f)
g = np.linspace(1,2,15)
print(g)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[1.         1.07142857 1.14285714 1.21428571 1.28571429 1.35714286
 1.42857143 1.5        1.57142857 1.64285714 1.71428571 1.78571429
 1.85714286 1.92857143 2.        ]


In [29]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
c = a+b
print(c)
d = a * b
print(d)

[11 22 33 44]
[ 10  40  90 160]


In [30]:
farenheit = np.array([0, -10, -5, -15, 0])
celcius = (farenheit - 31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [31]:
celcius > -20

array([ True, False, False, False,  True])

In [32]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])
A*B

array([[2, 0],
       [0, 4]])

In [33]:
A@B

array([[5, 4],
       [3, 4]])

In [34]:
A


array([[1, 1],
       [0, 1]])

In [35]:
B

array([[2, 0],
       [3, 4]])

In [36]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [37]:
a.ndim

1

In [38]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
b.shape

(2, 3)

In [40]:
a.dtype

dtype('int64')

In [41]:
c = np.array([1, 3.4, 5.0])
c.dtype

dtype('float64')

In [42]:
c

array([1. , 3.4, 5. ])

In [43]:
d = np.zeros((2,3))

In [44]:
d



array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
e = np.ones((2,3))
e

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
f = np.random.rand(2,3)
f

array([[0.54242276, 0.39029957, 0.43934697],
       [0.85194595, 0.63856259, 0.27729318]])

In [47]:
g = np.arange(11,50,2)
g

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

In [48]:
h = np.linspace(0,2,15)
h

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [49]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
c = a+b
c

array([11, 22, 33, 44])

In [50]:
d = a * b
d

array([ 10,  40,  90, 160])

In [51]:
a = np.array([1,2,3,4,5])
a[:3]

array([1, 2, 3])

In [52]:
a[1:7]

array([2, 3, 4, 5])

In [53]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [54]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [57]:
wines = np.genfromtxt("/home/nitin/work/coursera_python_datascience/resources/course1/week-1/datasets/winequality-red.csv", delimiter=";", skip_header=1)
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [58]:
wines_2 = wines[:,0]
wines_2.shape

(1599,)

In [59]:
wines[:, :1]

array([[7.4],
       [7.8],
       [7.8],
       ...,
       [6.3],
       [5.9],
       [6. ]])

In [60]:
wines_1  = wines[:, 0:1]
wines_1.shape

(1599, 1)

In [61]:
wines_3 = wines[:, ]
wines_3.shape

(1599, 12)

In [62]:
wines.shape

(1599, 12)

In [63]:
wines[:,-1].mean()

5.6360225140712945

In [64]:
graduate_admission = np.genfromtxt("/home/nitin/work/coursera_python_datascience/resources/course1/week-1/datasets/Admission_Predict.csv", dtype=None, delimiter=",", encoding=None)
graduate_admission

array([['Serial No.', 'GRE Score', 'TOEFL Score', ..., 'CGPA',
        'Research', 'Chance of Admit'],
       ['1', '337', '118', ..., '9.65', '1', '0.92'],
       ['2', '324', '107', ..., '8.87', '1', '0.76'],
       ...,
       ['398', '330', '116', ..., '9.45', '1', '0.91'],
       ['399', '312', '103', ..., '8.78', '0', '0.67'],
       ['400', '333', '117', ..., '9.66', '1', '0.95']], dtype='<U17')

In [65]:
graduate_admission = np.genfromtxt("/home/nitin/work/coursera_python_datascience/resources/course1/week-1/datasets/Admission_Predict.csv", dtype=None, delimiter=",",skip_header=1,
                                  names=('Serial No.','GRE Score','TOEFL Score','University Rating','SOP','LOR ','CGPA','Research','Chance of Admit'))
graduate_admission

array([(  1, 337, 118, 4, 4.5, 4.5, 9.65, 1, 0.92),
       (  2, 324, 107, 4, 4. , 4.5, 8.87, 1, 0.76),
       (  3, 316, 104, 3, 3. , 3.5, 8.  , 1, 0.72),
       (  4, 322, 110, 3, 3.5, 2.5, 8.67, 1, 0.8 ),
       (  5, 314, 103, 2, 2. , 3. , 8.21, 0, 0.65),
       (  6, 330, 115, 5, 4.5, 3. , 9.34, 1, 0.9 ),
       (  7, 321, 109, 3, 3. , 4. , 8.2 , 1, 0.75),
       (  8, 308, 101, 2, 3. , 4. , 7.9 , 0, 0.68),
       (  9, 302, 102, 1, 2. , 1.5, 8.  , 0, 0.5 ),
       ( 10, 323, 108, 3, 3.5, 3. , 8.6 , 0, 0.45),
       ( 11, 325, 106, 3, 3.5, 4. , 8.4 , 1, 0.52),
       ( 12, 327, 111, 4, 4. , 4.5, 9.  , 1, 0.84),
       ( 13, 328, 112, 4, 4. , 4.5, 9.1 , 1, 0.78),
       ( 14, 307, 109, 3, 4. , 3. , 8.  , 1, 0.62),
       ( 15, 311, 104, 3, 3.5, 2. , 8.2 , 1, 0.61),
       ( 16, 314, 105, 3, 3.5, 2.5, 8.3 , 0, 0.54),
       ( 17, 317, 107, 3, 4. , 3. , 8.7 , 0, 0.66),
       ( 18, 319, 106, 3, 4. , 3. , 8.  , 1, 0.65),
       ( 19, 318, 110, 3, 4. , 3. , 8.8 , 0, 0.63),
       ( 20,

In [66]:
graduate_admission.shape

(400,)

In [67]:
graduate_admission['CGPA'][0:5]

array([9.65, 8.87, 8.  , 8.67, 8.21])

In [68]:
graduate_admission['CGPA'] = graduate_admission['CGPA']/10 * 4
graduate_admission['CGPA'][:20]

array([3.86 , 3.548, 3.2  , 3.468, 3.284, 3.736, 3.28 , 3.16 , 3.2  ,
       3.44 , 3.36 , 3.6  , 3.64 , 3.2  , 3.28 , 3.32 , 3.48 , 3.2  ,
       3.52 , 3.4  ])

In [69]:
len(graduate_admission[graduate_admission['Research'] == 1])

219

In [70]:
print(graduate_admission[graduate_admission['Chance_of_Admit'] > 0.8]['GRE_Score'].mean())
print(graduate_admission[graduate_admission['Chance_of_Admit'] < 0.4]['GRE_Score'].mean())

328.7350427350427
302.2857142857143


In [71]:
import re

In [72]:
text = "This is a good day"
if re.search("good", text):
    print("Wonderful!")
else:
    print("Alas")

Wonderful!


In [73]:
text = "itin works dilligently. Nitin is a good boy. Nitin gets good grades."
found = re.search("^Nitin", text)
if found:
    print("string was found")
else:
    print("String was not found")

String was not found


In [74]:
grades = "ACAABDABCDBCADCCBADDCBBAACDB"
re.findall("B",grades)

['B', 'B', 'B', 'B', 'B', 'B', 'B']

In [75]:
re.findall("AB",grades)

['AB', 'AB']

In [76]:
re.findall("[AB]",grades)

['A', 'A', 'A', 'B', 'A', 'B', 'B', 'A', 'B', 'A', 'B', 'B', 'A', 'A', 'B']

In [77]:
re.findall("[A][A-D]",grades)

['AC', 'AA', 'AB', 'AD', 'AD', 'AA']

In [78]:
re.findall("AB|AC",grades)

['AC', 'AB', 'AB', 'AC']

In [79]:
re.findall("[^A]",grades)

['C',
 'B',
 'D',
 'B',
 'C',
 'D',
 'B',
 'C',
 'D',
 'C',
 'C',
 'B',
 'D',
 'D',
 'C',
 'B',
 'B',
 'C',
 'D',
 'B']

In [80]:
re.findall("^[^A]",grades)

[]

In [81]:
re.findall("AB{2,10}",grades)

[]

In [82]:
re.findall("A{1,1}A{1,1}",grades)

['AA', 'AA']

In [83]:
grades2 = "AABCDFEAAAAAdfffwefAA"
found = re.findall("A{1,1}A{1,1}",grades2)
if found:
    print(found)

['AA', 'AA', 'AA', 'AA']


In [84]:
with open('/home/nitin/work/coursera_python_datascience/resources/course1/week-1/datasets/ferpa.txt', 'r') as file:
    wiki = file.read()
    
wiki    
    


'Overview[edit]\nFERPA gives parents access to their child\'s education records, an opportunity to seek to have the records amended, and some control over the disclosure of information from the records. With several exceptions, schools must have a student\'s consent prior to the disclosure of education records after that student is 18 years old. The law applies only to educational agencies and institutions that receive funds under a program administered by the U.S. Department of Education.\n\nOther regulations under this act, effective starting January 3, 2012, allow for greater disclosures of personal and directory student identifying information and regulate student IDs and e-mail addresses.[2] For example, schools may provide external companies with a student\'s personally identifiable information without the student\'s consent.[2]\n\nExamples of situations affected by FERPA include school employees divulging information to anyone other than the student about the student\'s grades o

In [85]:
!pip install venv



ERROR: Could not find a version that satisfies the requirement venv (from versions: none)
ERROR: No matching distribution found for venv


In [86]:
import pandas as pd
# redshift_df = pd.read_csv('C:/Users/28586/Documents/work/Coursera/Files/home/jovyan/work/resources/course1/week-1/datasets/verification_logs_staging.csv', sep=',', dtype={
#     'verificationlogkey':'Int64', 
#     'distributor_id':object, 'provider_id': object, 'orderline_id': object, 'duration':'Int64', 'network_call_sign':object, 
#     'date_time_of_airing':object, 'title':object, 'segment':object, 'region':object,'status_code':'Int64', 'tenant':object, 
#     'recordinsertdate':object, 'recordupdatedate':object, 'activeflag':object, 'insertbatchid': 'Int64', 'updatebatchid': 'Int64' 
#        } )
# redshift_df.head(2)
# len(redshift_df)

In [87]:
# it will give all texts having chars(a-z or A-Z) (1-100) + word = edit
re.findall("[a-zA-Z]{1,100}\[edit\]",wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

In [88]:
# \s match any whitespace characters
re.findall("[\s]{0,100}\[edit\]",wiki)

['[edit]', '[edit]', '[edit]']

In [89]:
# * to match zero or more times w to match any character including numbers
re.findall("[\w]*\[edit\]", wiki)

['Overview[edit]', 'records[edit]', 'records[edit]']

In [90]:
re.findall("[\w ]*\[edit\]",wiki)

['Overview[edit]',
 'Access to public records[edit]',
 'Student medical records[edit]']

In [91]:
for title in re.findall("[\w ]*\[edit\]",wiki):
    print(re.split("[\[]",title)[0])

Overview
Access to public records
Student medical records


In [92]:
# group - it will find all the smaller patterns and find matching results
re.findall("([\w ]*)(\[edit\])",wiki)

[('Overview', '[edit]'),
 ('Access to public records', '[edit]'),
 ('Student medical records', '[edit]')]

In [93]:
for item in re.finditer("([\w ]*)(\[edit\])",wiki):
    print(item.groups())

('Overview', '[edit]')
('Access to public records', '[edit]')
('Student medical records', '[edit]')


In [94]:
# group(0) - whole match, each subsequent index is portion of match
for item in re.finditer("([\w ]*)(\[edit\])",wiki):
    print(item.group(1))

Overview
Access to public records
Student medical records


In [95]:
for item in re.finditer("(?P<title>[\w ]*)(?P<edit_link>\[edit\])",wiki):
    print(item.groupdict())

{'title': 'Overview', 'edit_link': '[edit]'}
{'title': 'Access to public records', 'edit_link': '[edit]'}
{'title': 'Student medical records', 'edit_link': '[edit]'}


In [96]:
for item in re.finditer("(?P<title>[\w ]+)(?=\[edit\])",wiki):
    print(item)

<re.Match object; span=(0, 8), match='Overview'>
<re.Match object; span=(2715, 2739), match='Access to public records'>
<re.Match object; span=(3692, 3715), match='Student medical records'>


In [97]:
with open('/home/nitin/work/coursera_python_datascience/resources/course1/week-1/datasets/buddhist.txt', mode='r') as file:
    budh = file.read()
    
budh    

'Buddhist universities and colleges in the United States\nFrom Wikipedia, the free encyclopedia\nJump to navigationJump to search\n\nThis article needs additional citations for verification. Please help improve this article by adding citations to reliable sources. Unsourced material may be challenged and removed.\nFind sources: "Buddhist universities and colleges in the United States" – news · newspapers · books · scholar · JSTOR (December 2009) (Learn how and when to remove this template message)\nThere are several Buddhist universities in the United States. Some of these have existed for decades and are accredited. Others are relatively new and are either in the process of being accredited or else have no formal accreditation. The list includes:\n\nDhammakaya Open University – located in Azusa, California, part of the Thai Wat Phra Dhammakaya[1]\nDharmakirti College – located in Tucson, Arizona Now called Awam Tibetan Buddhist Institute (http://awaminstitute.org/)\nDharma Realm Buddh

In [98]:
import logging
logging.basicConfig(level=logging.ERROR, force=True)
logging.debug('This message should go to the log file')
logging.info('So should this')
logging.warning('And this, too')
logging.error('And non-ASCII stuff, too, like Øresund and Malmö')

ERROR:root:And non-ASCII stuff, too, like Øresund and Malmö


In [99]:
pattern ="""
(?P<title>.*)         # university title
(-\ located\ in\ )    # indicator for location
(?P<city>\w*)         # city
(,\ )                 # separator for state
(?P<state>\w*)        # state                  """    
for item in re.finditer(pattern,budh,re.VERBOSE):
    print(item)

In [100]:
import re


In [101]:
txt = 'Nitin is a good boy. He is a good swimmer.'
if re.search('good',txt):
    print('wonderful')
else:
    print('oh no')

wonderful


In [102]:
print(re.search('good',txt))

<re.Match object; span=(11, 15), match='good'>


In [103]:
print(re.match('good',txt))

None


In [104]:
txt = 'He is a good boy. Nitin is hardworking. Nitin is a good swimmer.'
re.split('Nitin',txt)


['He is a good boy. ', ' is hardworking. ', ' is a good swimmer.']

In [105]:
re.findall('Nitin',txt)


['Nitin', 'Nitin']

In [106]:
print(re.search('Nitin',txt))

<re.Match object; span=(18, 23), match='Nitin'>


In [107]:
print(re.search('hardworking',txt))

<re.Match object; span=(27, 38), match='hardworking'>


In [108]:
grades = 'ABCABBCAACBCCBAACBABCAABC'
re.findall('A',grades)

['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A']

In [109]:
number_a = len(re.findall('A',grades))
number_a

9

In [110]:
re.findall('[AB]',grades)

['A',
 'B',
 'A',
 'B',
 'B',
 'A',
 'A',
 'B',
 'B',
 'A',
 'A',
 'B',
 'A',
 'B',
 'A',
 'A',
 'B']

In [111]:
re.findall('AB',grades)

['AB', 'AB', 'AB', 'AB']

In [112]:
re.findall('BA',grades)

['BA', 'BA']

In [113]:
re.findall('[A-B]',grades)

['A',
 'B',
 'A',
 'B',
 'B',
 'A',
 'A',
 'B',
 'B',
 'A',
 'A',
 'B',
 'A',
 'B',
 'A',
 'A',
 'B']

In [114]:
re.findall('AB|AC',grades)

['AB', 'AB', 'AC', 'AC', 'AB', 'AB']

In [115]:
re.findall('[A][BC]',grades)

['AB', 'AB', 'AC', 'AC', 'AB', 'AB']

In [117]:
re.findall('[AC]',grades)

['A',
 'C',
 'A',
 'C',
 'A',
 'A',
 'C',
 'C',
 'C',
 'A',
 'A',
 'C',
 'A',
 'C',
 'A',
 'A',
 'C']

In [117]:
re.findall('[^AC]',grades)

['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B']

In [118]:
re.findall("^[^BC]", grades)

['A']

In [156]:
url = 'I refer to https://google.com and I never refer http://www.baidu.com if I have htt://www.baidu.com to search h://www.baidu.com anything'


In [157]:
re.findall('(?<=[https]:\/\/)([a-zA-Z0-9.]*)',url)

['google.com', 'www.baidu.com', 'www.baidu.com', 'www.baidu.com']

In [158]:
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [376]:
s = 'ACBCAC'
re.findall('^AC',s)

['AC']

In [377]:
a1 = np.random.rand(4)
a1

array([0.05157019, 0.67764351, 0.01847179, 0.8870158 ])

In [378]:
a1.shape

(4,)

In [379]:
a2 = np.random.rand(4,1)
a2

array([[0.93883627],
       [0.31832717],
       [0.33727025],
       [0.82334224]])

In [380]:
a2.shape

(4, 1)

In [381]:
a3 = np.array([[1,2,3,4]])
a3

array([[1, 2, 3, 4]])

In [382]:
a3.shape

(1, 4)

In [383]:
a4 = np.arange(1,4,1)
a4

array([1, 2, 3])

In [384]:
a4.shape

(3,)

In [385]:
a5 = np.linspace(1,4,4)
a5

array([1., 2., 3., 4.])

In [386]:
a5.shape

(4,)

In [387]:
old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [405]:
simple_string = """Amy is 5 years old, and her sister Mary is 2 years old. 
    Ruth and Peter, their parents, have 3 kids."""
pattern = '[A-Z][a-z]*'
re.findall(pattern,simple_string)    

['Amy', 'Mary', 'Ruth', 'Peter']

In [406]:
with open('/home/nitin/work/coursera_python_datascience/assignments/course1_assignment1/assets/grades.txt', mode='r') as file:
    grades = file.read()
    
grades

'Ronald Mayr: A\nBell Kassulke: B\nJacqueline Rupp: A \nAlexander Zeller: C\nValentina Denk: C \nSimon Loidl: B \nElias Jovanovic: B \nStefanie Weninger: A \nFabian Peer: C \nHakim Botros: B\nEmilie Lorentsen: B\nHerman Karlsen: C\nNathalie Delacruz: C\nCasey Hartman: C\nLily Walker : A\nGerard Wang: C\nTony Mcdowell: C\nJake Wood: B\nFatemeh Akhtar: B\nKim Weston: B\nNicholas Beatty: A\nKirsten Williams: C\nVaishali Surana: C\nCoby Mccormack: C\nYasmin Dar: B\nRomy Donnelly: A\nViswamitra Upandhye: B\nKendrick Hilpert: A\nKillian Kaufman: B\nElwood Page: B\nMukti Patel: A\nEmily Lesch: C\nElodie Booker: B\nJedd Kim: A\nAnnabel Davies: A\nAdnan Chen: B\nJonathan Berg: C\nHank Spinka: B\nAgnes Schneider: C\nKimberly Green: A\nLola-Rose Coates: C\nRose Christiansen: C\nShirley Hintz: C\nHannah Bayer: B'

In [416]:
pattern = '([\w ]+)(?=: B)'
re.findall(pattern,grades)

['Bell Kassulke',
 'Simon Loidl',
 'Elias Jovanovic',
 'Hakim Botros',
 'Emilie Lorentsen',
 'Jake Wood',
 'Fatemeh Akhtar',
 'Kim Weston',
 'Yasmin Dar',
 'Viswamitra Upandhye',
 'Killian Kaufman',
 'Elwood Page',
 'Elodie Booker',
 'Adnan Chen',
 'Hank Spinka',
 'Hannah Bayer']

In [417]:
with open('/home/nitin/work/coursera_python_datascience/assignments/course1_assignment1/assets/logdata.txt', mode='r') as file:
    logs = file.read()
    
logs

'146.204.224.152 - feest6811 [21/Jun/2019:15:45:24 -0700] "POST /incentivize HTTP/1.1" 302 4622\n197.109.77.178 - kertzmann3129 [21/Jun/2019:15:45:25 -0700] "DELETE /virtual/solutions/target/web+services HTTP/2.0" 203 26554\n156.127.178.177 - okuneva5222 [21/Jun/2019:15:45:27 -0700] "DELETE /interactive/transparent/niches/revolutionize HTTP/1.1" 416 14701\n100.32.205.59 - ortiz8891 [21/Jun/2019:15:45:28 -0700] "PATCH /architectures HTTP/1.0" 204 6048\n168.95.156.240 - stark2413 [21/Jun/2019:15:45:31 -0700] "GET /engage HTTP/2.0" 201 9645\n71.172.239.195 - dooley1853 [21/Jun/2019:15:45:32 -0700] "PUT /cutting-edge HTTP/2.0" 406 24498\n180.95.121.94 - mohr6893 [21/Jun/2019:15:45:34 -0700] "PATCH /extensible/reinvent HTTP/1.1" 201 27330\n144.23.247.108 - auer7552 [21/Jun/2019:15:45:35 -0700] "POST /extensible/infrastructures/one-to-one/enterprise HTTP/1.1" 100 22921\n2.179.103.97 - lind8584 [21/Jun/2019:15:45:36 -0700] "POST /grow/front-end/e-commerce/robust HTTP/2.0" 304 14641\n241.114.1

In [474]:
sample = '146.204.224.152 - feest6811 [21/Jun/2019:15:45:24 -0700] "POST /incentivize HTTP/1.1" 302 4622\n197.109.77.178 - kertzmann3129 [21/Jun/2019:15:45:25 -0700] "DELETE /virtual/solutions/target/web+services HTTP/2.0" 203 26554\n156.127.178.177 - okuneva5222 [21/Jun/2019:15:45:27 -0700] "DELETE /interactive/transparent/niches/revolutionize HTTP/1.1" 416 14701\n100.32.205.59 - ortiz8891 [21/Jun/2019:15:45:28 -0700] "PATCH /architectures HTTP/1.0" 204 6048\n'

# pattern = '([\:\-\[\]\w\d.\"\/\s\+]*)(?=\n)'
# re.findall(pattern,sample)

pattern = """
(?P<host>[\d]+.[\d]+.[\d]+.[\d]+)
(\ -\ )
(?P<username>[\w-]*)
(\ \[)
(?P<time>\w*/\w*/.*)
(\]\s")
(?P<request>.*)
(")
"""
logs_list = []
for item in re.finditer(pattern,logs,re.VERBOSE):
    logs_list.append(item.groupdict())
len(logs_list)    

979